plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-include-cache
 
# Jekyl SEO Tag
title: Alpha's Manifesto
description: A black and white figure's thought-hive
locale: en
timezone: America/Toronto
url: https://blog.alphasmanifesto.com
logo: /assets/headerAlpha.png
twitter:
  username: AlphasManifesto
  card: summary

# Jekyll-paginate
paginate_path: /page/:num
paginate: 10

# Jekyll-feed
feed:
  path: atom.xml

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.23.0
minimal_mistakes_skin: dirt
baseurl: /
category_archive_path: /categories/#
tag_archive_path: /tags/#
permalink: /:year/:month/:day/:slug/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      words_per_minute: 200
      comments: true
      share: true
      related: true

comments:
  provider: "disqus"
  disqus:
    shortname: alphasmanifestoblog

search: true
search_provider: google
google:
  search_engine_id: ed903ebbf9cc19bb1
twitter:
  username: AlphasManifesto

analytics:
  provider: google-universal
  google: 
    tracking_id: UA-367009-7
    anonymize_ip: false

author:
  name: Juan Diego Raimondi
  avatar: /assets/avatarJD.jpg
  bio: Software engineer. Curious person. Very serious. Not a robot (yet).
  links:
    - title: Twitter
      url: https://twitter.com/AlphasManifesto
      icon: fab fa-twitter
    - title: LinkedIn
      url: https://www.linkedin.com/in/raimondijuan/
      icon: fab fa-linkedin
    - title: GitHub
      url: https://www.github.com/AlphaGit
      icon: fab fa-github