# based from https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Theme settings
# remote_theme: "mmistakes/minimal-mistakes@4.23.0"

# Site settings
locale: "en"
title: "Alpha's Manifesto"
title_separator: "|"
description: "A black and white figure's thought-hive"
name: "1"
url: "https://blog.alphasmanifesto.com"
baseurl: "/"
repository: "AlphaGit/alphas-manifesto-blog"
logo: "/assets/headerAlpha.png"
words_per_minute: 200
comments:
  provider: "disqus"
  disqus:
    shortname: "alphasmanifestoblog"
search: true
search_provider: google
google:
  search_engine_id: "ed903ebbf9cc19bb1"
  instant_search: true

# Social Sharing
twitter:
  username: "AlphasManifesto"

# Analytics
analytics:
  provider: "google-universal"
  google: 
    tracking_id: "UA-367009-7"

# Site Author
author:
  name: "JD Raimondi"
  avatar: "/assets/avatarJD.jpg"
  bio: "Software engineer. Curious person. Very serious. Not a robot (yet)."
  email: "raimondijuan@gmail.com"
  links:
    - label: "Twitter"
      url: "https://twitter.com/AlphasManifesto"
      icon: "fab fa-twitter"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/raimondijuan/"
      icon: "fab fa-linkedin"
    - label: "GitHub"
      url: "https://www.github.com/AlphaGit"
      icon: "fab fa-github"

# Outputting
permalink: /:year/:month/:day/:slug/
paginate: 10
paginate_path: /page/:num
timezone: America/Toronto

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults 
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
      excerpt_separator: <!--more-->

alphasmanifesto:
  date_format: "%b %-d, %Y"
  show_excerpts: true
  tag_archive_path: "/tags/#"
  subtitle: "A black and white figure's thought-hive"
  logo: /assets/headerAlpha.png
  logo_height: 85