title: Alpha's Manifesto
description: A black and white figure's thought-hive
locale: en
remote_theme: mmistakes/so-simple-theme@3.2.0
timezone: America/Toronto

author:
  name: Juan Diego Raimondi
  twitter: AlphasManifesto
  email: raimondijuan@gmail.com
  picture: /images/avatarJD.jpg
  links:
    - title: Twitter
      url: https://twitter.com/AlphasManifesto
      icon: fab fa-twitter
    - title: LinkedIn
      url: https://www.linkedin.com/in/raimondijuan/
      icon: fab fa-linkedin

read_time: true
words_per_minute: 150
mathjax: true
search_full_content: true

url: https://blog.alphasmanifesto.com
baseurl: /
category_archive_path: /categories/#
tag_archive_path: /tags/#
permalink: /:year/:month/:day/:slug/
paginate_path: /page/:num/
feed:
  path: atom.xml

disqus:
  shortname: alphasmanifestoblog

logo: images/headerAlpha.png

google_analytics: UA-367009-7

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-paginate
 - jekyll-feed
paginate: 10
