plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
 
# Jekyl SEO Tag

title: Alpha's Manifesto
description: A black and white figure's thought-hive
locale: en
remote_theme: mmistakes/so-simple-theme@3.2.0
timezone: America/Toronto
url: https://blog.alphasmanifesto.com
logo: images/headerAlpha.png
twitter:
  username: AlphasManifesto
  card: summary

paginate_path: /page/:num/
paginate: 10

# Jekyll-feed
feed:
  path: atom.xml

# So-Simple-Theme
disqus:
  shortname: alphasmanifestoblog

google_analytics: UA-367009-7
baseurl: /
category_archive_path: /categories/#
tag_archive_path: /tags/#
permalink: /:year/:month/:day/:slug/
read_time: true
words_per_minute: 150
mathjax:
  enable: true
search_full_content: true

author:
  name: Juan Diego Raimondi
  twitter: AlphasManifesto
  email: raimondijuan@gmail.com
  picture: /images/avatarJD.jpg
  links:
    - title: Twitter
      url: https://twitter.com/AlphasManifesto
      icon: fab fa-twitter
    - title: LinkedIn
      url: https://www.linkedin.com/in/raimondijuan/
      icon: fab fa-linkedin
