ruversion: "3.9"

services:
    jekyll:
        build: 
            context: .
            dockerfile: jekyll.Dockerfile
        ports: 
            - 4000:4000
        volumes: 
            - ./:/srv/jekyll